### ISSUE TITLE
Component Library & Footprint Design

### ISSUE THREAD

**Issue by neohere97** [neohere97/SkySync#17]
- [x] EFR32BG22 - @mrya3714 
- [x] ENS160 - @neohere97 
- [x] BME280 - @akash7071 (Apparently pin numbers is inverted)
- [x] F Antenna -  @akash7071 
- [x] AS7331 - @neohere97 
- [x] Inductor(s) - @mrya3714 (Needs Work)
- [x] LDO - @akash7071 
- [x] USBC connector - @neohere97 (needs work), Update to one Chris provided
- [x] LED - @mrya3714 
- [x] 0603 Capacitor/Resistor - @mrya3714 
- [x] BQ5570 - @neohere97
- [x] NLAST Load Switch - @neohere97 
- [x] Si1133 - @neohere97 
- [x] Schottkey Diodes - @neohere97 
- [x] Solar Panel - @neohere97 
- [x] JST Female Connector - @neohere97 
- [x] Button(s), Power switch, DIP Switches - @neohere97 
- [x] Ferrite Bead - @neohere97 
- [x] Display connector - @neohere97 
- [ ] Header Pins - @neohere97 
- [x] ESD Diode - @neohere97

**Comment by mrya3714** [comment]
Schematic refernce : [https://www.silabs.com/documents/public/schematic-files/BRD4184A-A01-schematic.pdf](url)

**Comment by neohere97** [comment]
@akash7071 Designator is on Top Layer and Pads need to be rounded rectangle ?

**Comment by neohere97** [comment]
AS7331 Currently finished but needs cross verification, USB C imported from SnapEDA needs cross verification. 

Guys @akash7071 @mrya3714 I have imported the PMIC and USBC from SnapEDA, both need to be verified and modified

**Comment by mrya3714** [comment]
PMIC Buck converter Inductor 10uH: [https://www.digikey.com/en/products/detail/w%C3%BCrth-elektronik/744029100/1638496?s=N4IgTCBcDaIOwBYEAYwE4CMzkAIQF0BfIA](url)

**Comment by mrya3714** [comment]
PMIC Boost converter Inductor 22 uH : [https://www.we-online.com/components/products/datasheet/744031220.pdf](url)

**Comment by neohere97** [comment]
https://www.digikey.com/en/products/detail/jst-sales-america-inc/BM02B-SRSS-TB/926694 - JST Micro Connector

https://www.digikey.com/en/products/detail/anysolar-ltd/SM141K06L/9990462
Solar Panel

**Comment by neohere97** [comment]
.
