### ISSUE TITLE
Project Update Format

### ISSUE THREAD

**Issue by mrya3714** [neohere97/SkySync#7]
[https://onedrive.live.com/edit.aspx?resid=8CCC3EE29A4AA332!140665&ithint=file%2cdocx&wdo=2&authkey=!ABEhoVeMhqTF0f0](https://onedrive.live.com/edit.aspx?resid=8CCC3EE29A4AA332!140665&ithint=file%2cdocx&wdo=2&authkey=!ABEhoVeMhqTF0f0)

**Comment by neohere97** [comment]
### **SoC**

EM2-Wakeup->Measure Data->Transfer Data->EM2

Assuming a 10 minute cycle, 30s in EM0 mode and 570s in EM2 mode with Radio on


EM2 - Full RAM retention and RTC running from LFRCO in precision
mode

| State         | Current (mA) | Power (mW) | Weight | 
|-------------------|--------------|-------------|
| EM2  | 0.7 | 2.31 | 0.95 | 
| EM0  | 6 |  19.8 | 0.05 | 

The average currents for EM2 and EM0 have been referred from IoT project numbers. 

Weighted Average of Current = **0.965mA**, at 3.3V 
Weighted Average of Power = 0.965 * 3.3 = **3.1845mW**

### BME280

In weather monitoring mode.

| State         | Current (mA) |  Weight |
|-------------------|--------------| ------------|
| Deep Sleep  |   0.0001  | 0.98  |
| Active           | 0.7  |  0.02  |

Needs about 8ms to wakeup and measure data.

Considering one data measurement every 10 minutes. 

Weighted Average Current = **0.01437mA**, at 3.3V

### ENS160

| State         | Current (mA) |  Weight |
|-------------------|--------------| ------------|
| Deep Sleep  |   0.01  | 0.7  |
| Active           | 29  |  0.3  |

The sensor needs 3 minutes to warm up, considering one measurement every 10minutes

Weighted Average Current = **8.7mA**, at 1.8V

### AS7331

| State         | Current (mA) |  Weight |
|-------------------|--------------| ------------|
| Deep Sleep  |   0.001  | 0.98  |
| Active           | 2  |  0.02  |

Needs about 70ms to wakeup and measure data.

Considering one data measurement every 10 minutes. 

Weighted Average Current = **0.0401mA**, at 3.3V
